"use client"
import ListView from "@/Component/HomePage/ListView"
import React, { useState } from "react"

// export const metadata = {

//     title: " ",
//     description: "Generated by create next app",
// };

export default function ListedData() {
    const [listData, setListData] = useState([]);
    const [ListSearch, setListSearch] = useState(false);
    const [loaderList, setLoaderList] = useState(false)
    return (
        <>
            {/* <HomeHeader/> */}
            {/* <FilterJob/> */}
            <ListView listData={listData} setListData={setListData} ListSearch={ListSearch} setListSearch={setListSearch} loaderList={loaderList} setLoaderList={setLoaderList} />
        </>
    )
}